# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy MASTER to production server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update files
        uses: appleboy/scp-action@master
        with:
          host: mciawebserver.upc.edu
          username: mcia
          key: ${{ secrets.ESXIREVERSEPROXY_PRIVATE_KEY }}
          port: 22
          source: "src/init.sh, src/delete.sh, config.sh, docker-compose.yaml, data/nginx/app.conf"
          target: "~/ESXiReverseProxy/"
      - name: Reload service
        uses: appleboy/ssh-action@master
        with:
          host: mciawebserver.upc.edu
          username: mcia
          key: ${{ secrets.ESXIREVERSEPROXY_PRIVATE_KEY }}
          port: 22
          envs: TOKEN, USER, ACTOR, REPO
          # script uses jq to parse JSON, make sure jq is installed on target server
          script: |
            cd ESXiReverseProxy
            ./src/init.sh
            docker-compose up --build -d
